###
# api/course
###

GET http://localhost:8000/api/course

###

GET    http://localhost:8000/api/course/{id}

###

PUT    http://localhost:8000/api/course/{id}
content-type: application/json

{
  "name": "test course name"
}

###

POST http://localhost:8000/api/course
content-type: application/json

{
  "name": "new course name"
}

###

DELETE http://localhost:8000/api/course/{id}

###
# api/person
###

GET    http://localhost:8000/api/person

###

GET    http://localhost:8000/api/person/{name}

###

PUT    http://localhost:8000/api/person/{name}
content-type: application/json

{
  "first_name": "first_name",
  "last_name": "last_name",
  "type": "student",
  "age": 0,
  "courses": [
    1,
    2
  ]
}

###

POST http://localhost:8000/api/person
content-type: application/json

{
  "first_name": "first_name",
  "last_name": "last_name",
  "type": "student",
  "age": 0,
  "courses": [
    1,
    2
  ]
}

###

DELETE http://localhost:8000/api/person/{name}

###