// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "go-api-tech-challenge/internal/models"
)

// CourseLister is an autogenerated mock type for the CourseLister type
type CourseLister struct {
	mock.Mock
}

// ListCourses provides a mock function with given fields: ctx
func (_m *CourseLister) ListCourses(ctx context.Context) ([]models.Course, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCourses")
	}

	var r0 []models.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Course, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Course); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCourseLister creates a new instance of CourseLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseLister {
	mock := &CourseLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
