// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "go-api-tech-challenge/internal/models"
)

// CourseCreator is an autogenerated mock type for the CourseCreator type
type CourseCreator struct {
	mock.Mock
}

// CreateCourse provides a mock function with given fields: ctx, courseName
func (_m *CourseCreator) CreateCourse(ctx context.Context, courseName string) (models.Course, error) {
	ret := _m.Called(ctx, courseName)

	if len(ret) == 0 {
		panic("no return value specified for CreateCourse")
	}

	var r0 models.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Course, error)); ok {
		return rf(ctx, courseName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Course); ok {
		r0 = rf(ctx, courseName)
	} else {
		r0 = ret.Get(0).(models.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, courseName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCourseCreator creates a new instance of CourseCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseCreator {
	mock := &CourseCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
