// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CourseDeleter is an autogenerated mock type for the CourseDeleter type
type CourseDeleter struct {
	mock.Mock
}

// DeleteCourse provides a mock function with given fields: ctx, courseID
func (_m *CourseDeleter) DeleteCourse(ctx context.Context, courseID int) error {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCourse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseDeleter creates a new instance of CourseDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseDeleter {
	mock := &CourseDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
