// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "go-api-tech-challenge/internal/models"
)

// CourseUpdater is an autogenerated mock type for the CourseUpdater type
type CourseUpdater struct {
	mock.Mock
}

// UpdateCourse provides a mock function with given fields: ctx, courseID, courseName
func (_m *CourseUpdater) UpdateCourse(ctx context.Context, courseID int, courseName string) (models.Course, error) {
	ret := _m.Called(ctx, courseID, courseName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCourse")
	}

	var r0 models.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (models.Course, error)); ok {
		return rf(ctx, courseID, courseName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) models.Course); ok {
		r0 = rf(ctx, courseID, courseName)
	} else {
		r0 = ret.Get(0).(models.Course)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, courseID, courseName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCourseUpdater creates a new instance of CourseUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseUpdater {
	mock := &CourseUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
