// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "go-api-tech-challenge/internal/models"
)

// PersonCreator is an autogenerated mock type for the PersonCreator type
type PersonCreator struct {
	mock.Mock
}

// CreatePerson provides a mock function with given fields: ctx, newPerson
func (_m *PersonCreator) CreatePerson(ctx context.Context, newPerson models.Person) (models.Person, error) {
	ret := _m.Called(ctx, newPerson)

	if len(ret) == 0 {
		panic("no return value specified for CreatePerson")
	}

	var r0 models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Person) (models.Person, error)); ok {
		return rf(ctx, newPerson)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Person) models.Person); ok {
		r0 = rf(ctx, newPerson)
	} else {
		r0 = ret.Get(0).(models.Person)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Person) error); ok {
		r1 = rf(ctx, newPerson)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPersonCreator creates a new instance of PersonCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonCreator {
	mock := &PersonCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
