// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "go-api-tech-challenge/internal/models"
)

// PersonLister is an autogenerated mock type for the PersonLister type
type PersonLister struct {
	mock.Mock
}

// ListPersons provides a mock function with given fields: ctx
func (_m *PersonLister) ListPersons(ctx context.Context) ([]models.Person, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPersons")
	}

	var r0 []models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Person, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Person); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPersonLister creates a new instance of PersonLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonLister {
	mock := &PersonLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
