// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PersonDeleter is an autogenerated mock type for the PersonDeleter type
type PersonDeleter struct {
	mock.Mock
}

// DeletePerson provides a mock function with given fields: ctx, lastName
func (_m *PersonDeleter) DeletePerson(ctx context.Context, lastName string) error {
	ret := _m.Called(ctx, lastName)

	if len(ret) == 0 {
		panic("no return value specified for DeletePerson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, lastName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPersonDeleter creates a new instance of PersonDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonDeleter {
	mock := &PersonDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
