// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "go-api-tech-challenge/internal/models"
)

// PersonGetter is an autogenerated mock type for the PersonGetter type
type PersonGetter struct {
	mock.Mock
}

// GetPersonByName provides a mock function with given fields: ctx, name
func (_m *PersonGetter) GetPersonByName(ctx context.Context, name string) (models.Person, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonByName")
	}

	var r0 models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Person, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Person); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(models.Person)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPersonGetter creates a new instance of PersonGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonGetter {
	mock := &PersonGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
